'use client'

import Link from 'next/link'
import { ArrowRight, Shield, Zap, Users } from 'lucide-react'
import { motion, useInView, useMotionValue, useTransform, animate } from 'framer-motion'
import { useEffect, useRef, useState } from 'react'
import FloatingOrbs from '@/components/shared/FloatingOrbs'

function CountUp({ to, suffix = '' }: { to: number; suffix?: string }) {
  const ref = useRef<HTMLSpanElement>(null)
  const inView = useInView(ref, { once: true })
  const count = useMotionValue(0)
  const rounded = useTransform(count, (v) => Math.round(v).toLocaleString() + suffix)

  useEffect(() => {
    if (!inView) return
    const controls = animate(count, to, { duration: 1.8, ease: 'easeOut' })
    return controls.stop
  }, [inView, count, to])

  return <motion.span ref={ref}>{rounded}</motion.span>
}

const stats = [
  { label: 'Plans Generated', value: 2400, suffix: '+' },
  { label: 'Active Users', value: 850, suffix: '+' },
  { label: 'Goal Hit Rate', value: 94, suffix: '%' },
]

const trustBadges = [
  { icon: Shield, label: 'Plans validated by consensus' },
  { icon: Zap, label: 'Powered by GenLayer AI' },
  { icon: Users, label: 'Results stored on-chain' },
]

export default function Hero() {
  const [ready, setReady] = useState(false)
  useEffect(() => setReady(true), [])

  return (
    <section className="relative min-h-screen flex items-center justify-center pt-16 overflow-hidden">
      {/* Aurora background */}
      <div className="absolute inset-0 aurora-bg pointer-events-none" />

      {/* Floating orbs */}
      <FloatingOrbs />

      {/* Grid texture */}
      <div className="absolute inset-0 bg-grid-pattern opacity-40 pointer-events-none" />

      {ready && (
        <div className="container mx-auto px-4 text-center relative z-10">
          {/* Badge */}
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: 'easeOut' }}
            className="inline-flex items-center gap-2 glass px-4 py-2 rounded-full text-sm mb-8"
          >
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-mauve opacity-75" />
              <span className="relative inline-flex h-2 w-2 rounded-full bg-plum dark:bg-peach" />
            </span>
            <span className="text-muted-foreground">Powered by</span>
            <span className="text-plum dark:text-peach font-semibold">GenLayer Intelligent Contracts</span>
          </motion.div>

          {/* Headline */}
          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.1, ease: 'easeOut' }}
            className="text-5xl md:text-7xl font-bold tracking-tight leading-tight mb-6"
          >
            Your AI Fitness Plan,
            <br />
            <span className="text-gradient">Verified On-Chain.</span>
          </motion.h1>

          {/* Subheadline */}
          <motion.p
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-10"
          >
            Submit your fitness profile and receive a personalized workout + nutrition plan
            generated by AI and validated by GenLayer's multi-validator consensus — trustworthy,
            consistent, and owned by you.
          </motion.p>

          {/* CTAs */}
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16"
          >
            <motion.div whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.97 }}>
              <Link
                href="/signup"
                className="flex items-center gap-2 btn-primary text-base px-8 py-4 glow w-full sm:w-auto justify-center"
              >
                Get My Fitness Plan <ArrowRight className="w-5 h-5" />
              </Link>
            </motion.div>
            <motion.div whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.97 }}>
              <a
                href="#how-it-works"
                className="flex items-center gap-2 glass px-8 py-4 rounded-xl hover:bg-plum/10 dark:hover:bg-white/10 transition-all text-base w-full sm:w-auto justify-center font-medium"
              >
                See How It Works
              </a>
            </motion.div>
          </motion.div>

          {/* Trust badges */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-6 mb-16 text-sm text-muted-foreground"
          >
            {trustBadges.map(({ icon: Icon, label }) => (
              <div key={label} className="flex items-center gap-2">
                <Icon className="w-4 h-4 text-mauve" />
                <span>{label}</span>
              </div>
            ))}
          </motion.div>

          {/* Stats with count-up */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.5 }}
            className="grid grid-cols-3 gap-4 max-w-lg mx-auto"
          >
            {stats.map((s) => (
              <div
                key={s.label}
                className="glass rounded-xl p-4 card-hover group border border-border/40"
              >
                <div className="text-2xl font-bold text-plum dark:text-peach">
                  <CountUp to={s.value} suffix={s.suffix} />
                </div>
                <div className="text-xs text-muted-foreground mt-1">{s.label}</div>
              </div>
            ))}
          </motion.div>
        </div>
      )}
    </section>
  )
}
