'use client'

import Link from 'next/link'
import { ArrowRight, Shield, Zap, Users } from 'lucide-react'
import { motion } from 'framer-motion'

const stats = [
  { label: 'Plans Generated', value: '2,400+' },
  { label: 'Active Users', value: '850+' },
  { label: 'Avg. Goal Hit Rate', value: '94%' },
]

export default function Hero() {
  return (
    <section className="relative min-h-screen flex items-center justify-center pt-16 overflow-hidden">
      {/* Background glow */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-[#00FF88]/5 rounded-full blur-[120px]" />
        <div className="absolute top-2/3 left-1/4 w-[400px] h-[400px] bg-[#00FF88]/3 rounded-full blur-[80px]" />
      </div>

      <div className="container mx-auto px-4 text-center relative z-10">
        {/* Badge */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="inline-flex items-center gap-2 glass px-4 py-2 rounded-full text-sm mb-8"
        >
          <div className="w-2 h-2 bg-[#00FF88] rounded-full animate-pulse" />
          <span className="text-muted-foreground">Powered by</span>
          <span className="text-[#00FF88] font-medium">GenLayer Intelligent Contracts</span>
        </motion.div>

        {/* Headline */}
        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="text-5xl md:text-7xl font-bold tracking-tight leading-tight mb-6"
        >
          Your AI Fitness Plan,
          <br />
          <span className="text-gradient">Verified On-Chain.</span>
        </motion.h1>

        {/* Subheadline */}
        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-10"
        >
          Submit your fitness profile and receive a personalized workout + nutrition plan
          generated by AI and validated by GenLayer's multi-validator consensus — trustworthy,
          consistent, and owned by you.
        </motion.p>

        {/* CTAs */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.3 }}
          className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16"
        >
          <Link
            href="/signup"
            className="flex items-center gap-2 bg-[#00FF88] text-black font-semibold px-8 py-4 rounded-xl hover:bg-[#00E87A] transition-all glow text-base w-full sm:w-auto justify-center"
          >
            Get My Fitness Plan <ArrowRight className="w-5 h-5" />
          </Link>
          <a
            href="#how-it-works"
            className="flex items-center gap-2 glass px-8 py-4 rounded-xl hover:bg-white/10 transition-all text-base w-full sm:w-auto justify-center"
          >
            See How It Works
          </a>
        </motion.div>

        {/* Trust badges */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.4 }}
          className="flex flex-col sm:flex-row items-center justify-center gap-6 mb-16 text-sm text-muted-foreground"
        >
          <div className="flex items-center gap-2">
            <Shield className="w-4 h-4 text-[#00FF88]" />
            <span>Plans validated by consensus</span>
          </div>
          <div className="flex items-center gap-2">
            <Zap className="w-4 h-4 text-[#00FF88]" />
            <span>Powered by GenLayer AI</span>
          </div>
          <div className="flex items-center gap-2">
            <Users className="w-4 h-4 text-[#00FF88]" />
            <span>Results stored on-chain</span>
          </div>
        </motion.div>

        {/* Stats */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.5 }}
          className="grid grid-cols-3 gap-4 max-w-lg mx-auto"
        >
          {stats.map((s) => (
            <div key={s.label} className="glass rounded-xl p-4">
              <div className="text-2xl font-bold text-[#00FF88]">{s.value}</div>
              <div className="text-xs text-muted-foreground mt-1">{s.label}</div>
            </div>
          ))}
        </motion.div>
      </div>
    </section>
  )
}
